name: dim_flutter
description: DIM Flutter Client
version: 1.0.0
homepage: https://github.com/dimchat/demo-flutter
repository: https://github.com/dimchat/demo-flutter
issue_tracker: https://github.com/dimchat/demo-flutter/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  plugin_platform_interface: ^2.0.2
  device_info_plus: ^9.1.2
  package_info_plus: ^7.0.0

  permission_handler: ^12.0.0
  permission_handler_android: ^13.0.0
  path: ^1.8.3
  path_provider: ^2.1.2

  shared_preferences: ^2.2.2
  get: ^4.6.6

  sqflite: ^2.2.6
#  sqflite_common_ffi: ^2.3.3
#  sqflite_common_ffi_web: ^0.4.2
#
#  fvp: ^0.16.1
  video_player: ^2.8.3
  chewie: ^1.8.1
  castscreen: ^1.0.2

  photo_view: ^0.14.0
  image_picker: ^1.1.2
  image_gallery_saver: ^2.0.3
  flutter_image_compress: ^2.3.0
  flutter_inappwebview: ^6.0.0
#  webview_windows: ^0.4.0
  url_launcher: ^6.3.0

  flutter_markdown: ^0.6.19
#  markdown: ^7.2.1
  syntax_highlight: ^0.4.0

  flutter_section_list: ^1.1.1
  #  flutter_tableview: ^1.0.1
  #  tableview: ^0.0.3

  #  wakelock_plus: 1.1.6

  bip32: ^2.0.0
  bip39: ^1.0.6

  mutex: ^3.1.0

#  object_key: 1.1.0
#  lnc: 1.1.0
#  startrek: 1.1.0
#  stargate: 1.0.0

#  mkm: 2.1.0
#  dkd: 2.1.0
#  dimp: 2.1.0
#  dimsdk: 2.1.0
#  dim_plugins: 2.1.0
  dim_client: 1.0.1

  pnf: 1.2.2
  tvbox: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: chat.dim.dim_flutter
        pluginClass: DimFlutterPlugin
      ios:
        pluginClass: DimFlutterPlugin
      linux:
        pluginClass: DimFlutterPlugin
      macos:
        pluginClass: DimFlutterPlugin
      windows:
        pluginClass: DimFlutterPluginCApi
      web:
        pluginClass: DimFlutterWeb
        fileName: dim_flutter_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
